### ISSUE TITLE
2nd day

### ISSUE THREAD

**Issue by Avi-Cohen** [ShlomiHillel/safe-city#2]
1) Create "views" folder with: npx create-react-app views at the top directory.
2) Connect react with express 
- you can write a simple route in order to check it
- make sure the front and the back are running on different ports
- be aware to CORS/Parsing issues 
3) Update the package.json with the correct scripts
- check scripts, run them locally
4) (optional): create a http get request from the front to the back
- check network tab to see if it went through with an OK status

**Comment by Avi-Cohen** [comment]
Also: 
- add "about" for the repo (Short - 1 sentence)
- add .gitignore file and remove node modules from the repo (node_modules/)

// you can comment in here if you have any questions or when you done (I check it daily)

**Comment by ShlomiHillel** [comment]
I will do that today

**Comment by ShlomiHillel** [comment]
i have a few more things to fix, but i think that i completed the hard part of this task.
i will be happy to recive the next task.

toda.
shlomi
